backend:
  name: github
  repo: AviZurlo/personal-site
  branch: main
  base_url: https://avi.dog
  auth_endpoint: api/auth/github

media_folder: "public/images/articles"
public_folder: "/images/articles"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Source", name: "source", widget: "select", options: ["original", "mirror", "x"], default: "original"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
